version: '3'

services:
  backend:
    container_name: backend
    image: andreymerlov/andreymerlov:auth_backend
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - MONGODB_URI=DB_URL
    networks:
      - app-network

  frontend:
    container_name: frontend
    image: andreymerlov/andreymerlov:auth_frontend
    ports:
      - "4000:80"
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge